version: "3.8"  # 최신 Docker Compose 버전 사용

services:
  ai-training:
    build: .  # 현재 디렉터리의 Dockerfile로 이미지 빌드
    container_name: coral_deeplab_trainer  # 컨테이너 이름 (선택 사항)

    command: tail -f /dev/null  # 컨테이너가 종료되지 않도록 유지

    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # 모든 GPU를 컨테이너에 노출

    volumes:
      - ./:/workspace  # 프로젝트 루트 폴더를 /workspace로 마운트
      - /home/shpark/workspace/merged_all:/workspace/merged_all  # 데이터셋 마운트
      - /home/allbigdat/data:/workspace/data  # DATA_CFG.root_path 마운트

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']  # 사용할 GPU ID를 명시 (예: '0', '1' 등)

    # (선택) 포트 매핑 - 필요한 경우에만 활성화
    # ports:
    #   - "8888:8888"  # 예: Jupyter Notebook 접속용
    #   - "6006:6006"  # 예: TensorBoard 접속용
